site_name: do-devops-projects
site_url: https://do-devops-projects.readthedocs.io
repo_url: https://github.com/deoluoyinlola/do-devops-projects
strict: true
theme:
  name: material
  palette:
    primary: indigo
  font:
    text: 'Roboto'
  logo: 'assets/logo.jpeg'
extra_css:
  - 'assets/extra.css'
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
  - About: about/index.md
  - Free Self-Paced:
    - Intro: about/intro.md
    - Week 1: week1/week1.md
    - Week 2: week2/week2.md
    - Week 3: week3/week3.md
    - Week 4: week4/week4.md
    - Week 5: week5/week5.md
    - Week 6: week6/week6.md
    - Week 7: week7/week7.md
    - Week 8: week8/week8.md
  - Premium Study-Group:
    - Details: details.md
  - Don Circle:
    - Don-circle: don-circle.md
  
